rootLogger.level = WARN
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5level %msg%n

logger.reconfig.name = org.apache.logging.log4j.core.config
logger.reconfig.level = OFF